name: Build Windows Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install WiX
      run: dotnet tool install --global wix

    - name: Get Pharo Image and VM
      run: |
        mkdir pharo
        cd pharo
        curl https://get.pharo.org/120+vm | bash
        cd ..

    - name: Load Cormas
      run: |
        ./pharo/pharo ./pharo/Pharo.image eval "Metacello new repository: 'github://cormas/cormas/'; baseline: 'Cormas'; load. Smalltalk snapshot: true andQuit: true"
      
    - name: Test Pharo Installation
      run: |
        ./pharo/pharo ./pharo/Pharo.image eval " Metacello new repository: 'github://cormas/ecec-model:main'; baseline: 'ECECModel'; load. Smalltalk snapshot: true andQuit: true"
        ./pharo/pharo ./pharo/Pharo.image eval "| simulation | simulation := (CMSimulation for: ECECModel) activeInitSelector: #homogeneousEnvironment; activeControlSelector: #step:; initializeSimulation. simulation runAllStepsAfterEachDo: [ Transcript show: 'Simulation step '; show: simulation currentTimeStep asString; cr ]. Transcript show: simulation data last; cr"

    - name: Build the Application
      run: |
        echo "#include <stdio.h>`n`nint main(int argc, char* argv[]) {`n`tprintf(""Hello world\n"");`n`treturn 0;`n}" > hello.c
        cat hello.c
        gcc hello.c -o cormas.exe
        .\cormas.exe

    - name: Build MSI Installer
      run: wix build .\scripts\installers\cormas-windows.wxs -o cormas.msi

    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cormas-windows
        path: cormas.msi
