name: Build Windows Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install WiX
      run: dotnet tool install --global wix

    - name: Get Pharo Image and VM
      run: |
        mkdir pharo
        cd pharo
        curl https://get.pharo.org/120+vm | bash
        cd ..

    - name: Load Cormas
      run: |
        ./pharo/pharo ./pharo/Pharo.image eval "Metacello new repository: 'github://cormas/cormas/'; baseline: 'Cormas'; load. Smalltalk snapshot: true andQuit: true"
      
    - name: Build MSI Installer
      run: wix build .\installers\windows\cormas.wxs -o cormas-windows-64bit.msi  

    - name: Continuous Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          cormas-windows-64bit.msi
