name: Build Windows Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install WiX
      run: dotnet tool install --global wix

    - name: Build the Application
      run: |
        echo "#include <stdio.h>`n`nint main(int argc, char* argv[]) {`n`tprintf(""Hello world\n);""`n`treturn 0;`n}" > hello.c
        cat hello.c
        gcc hello.c -o cormas.exe
        .\cormas.exe

    - name: Build MSI Installer
      run: wix build scripts\installers\cormas-windows.wsx
